# Site settings
title: NeoEMF
email: neoemf@googlegroups.com
description: NeoEMF website
baseurl: ""
url: http://neoemf.github.io
repository: neoemf/neoemf.github.io

twitter_username: NeoEMF
github_username: atlanmod/NeoEMF

# Build settings
markdown: kramdown
