# Site settings
title: NeoEMF
email: neoemf@googlegroups.com
description: NeoEMF website
baseurl: ""
url: "http://www.neoemf.com"

twitter_username: NeoEMF
github_username: atlanmod/NeoEMF

# Build settings
markdown: kramdown
