name: Antora Site Build

on:
  push:
    branches: [ master ]

jobs:
  antora-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Generate Antora Site
        run: npm run build
      - name: Show contents
        run: ls -al ./doc
	  - name: Tell Jekyll to ignore Antora files
	    run: touch doc/.nojekyll
